name: flutter_toolbox
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - packages/notifications
  - packages/state_helpers
  - packages/result
  - packages/tb_dio
  - packages/tb_force_update

dev_dependencies:
  melos: ^7.4.0
