name: flutter_toolbox
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - packages/notifications
  - packages/state_helpers
  - packages/tb_result
  - packages/tb_dio
  - packages/tb_force_update
  - packages/tb_storage

dev_dependencies:
  melos: ^7.4.0
